build_type:
    wk_gzsx:
        display_name: '问酷高中数学'
        bundle_id: 'com.iasku.highmath.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzsx/'
        provision_file: 'HighMathIphone__Distribution.mobileprovision'
    wk_gzyw:
        display_name: '问酷高中语文'
        bundle_id: 'com.iasku.highchinese.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzyw/'
        provision_file: 'HighChineseIphone__Distribution.mobileprovision'
    wk_czhx:
        display_name: '问酷初中化学'
        bundle_id: 'com.iasku.juniorchemistry.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_czhx/'
        provision_file: 'JuniorChemistryIphone__Distribution.mobileprovision'
    wk_czkx:
        display_name: '问酷初中科学'
        bundle_id: 'com.iasku.juniorscience.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_czkx/'
        provision_file: 'JuniorScienceIphone__Distribution.mobileprovision'
    wk_czsx:
        display_name: '问酷初中数学'
        bundle_id: 'com.iasku.juniormath.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_czsx/'
        provision_file: 'JuniorMathIphone__Distribution.mobileprovision'
    wk_czwl:
        display_name: '问酷初中物理'
        bundle_id: 'com.iasku.juniorphysics.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_czwl/'
        provision_file: 'JuniorPhysicsIphone__Distribution.mobileprovision'
    wk_czyw:
        display_name: '问酷初中语文'
        bundle_id: 'com.iasku.juniorchinese.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_czyw/'
        provision_file: 'JuniorChineseIphone__Distribution.mobileprovision'
    wk_czyy:
        display_name: '问酷初中英语'
        bundle_id: 'com.iasku.juniorenglish.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_czyy/'
        provision_file: 'JuniorEnglishIphone__Distribution.mobileprovision'
    wk_gzdl:
        display_name: '问酷高中地理'
        bundle_id: 'com.iasku.highgeography.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzdl/'
        provision_file: 'HighGeographyIphone__Distribution.mobileprovision'
    wk_gzhx:
        display_name: '问酷高中化学'
        bundle_id: 'com.iasku.highchemistry.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzhx/'
        provision_file: 'HighChemistryIphone__Distribution.mobileprovision'
    wk_gzls:
        display_name: '问酷高中历史'
        bundle_id: 'com.iasku.highhistory.iphonee'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzls/'
        provision_file: 'HighHistoryIphone__Distribution.mobileprovision'
    wk_gzsw:
        display_name: '问酷高中生物'
        bundle_id: 'com.iasku.highbiology.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzsw/'
        provision_file: 'HighBiologyIphone__Distribution.mobileprovision'
    wk_gzwl:
        display_name: '问酷高中物理'
        bundle_id: 'com.iasku.highphysics.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzwl/'
        provision_file: 'HighPhysicsIphone__Distribution.mobileprovision'
    wk_gzyy:
        display_name: '问酷高中英语'
        bundle_id: 'com.iasku.highenglish.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzyy/'
        provision_file: 'HighEnglishIphone__Distribution.mobileprovision'
    wk_gzzz:
        display_name: '问酷高中政治'
        bundle_id: 'com.iasku.highpolitics.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_gzzz/'
        provision_file: 'HighPoliticsIphone__Distribution.mobileprovision'
    wk_xxsx:
        display_name: '问酷小学数学'
        bundle_id: 'com.iasku.primarymath.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_xxsx/'
        provision_file: 'PrimaryMathIphone_Distribution.mobileprovision'
    wk_xxyw:
        display_name: '问酷小学语文'
        bundle_id: 'com.iasku.primarychinese.iphone'
        scheme: 'iAsku'
        target: 'iAsku'
        provision_dir: './inhouse/wk_xxyw/'
        provision_file: 'PrimaryChineseIphone__Distribution.mobileprovision'
